la2pdf commit - 2012:03:02	15:06:39	(Fri 2.Mar)

diff --git a/LCAforActiveSonarImaging/bin/la2pdf b/LCAforActiveSonarImaging/bin/la2pdf
--- a/LCAforActiveSonarImaging/bin/la2pdf
+++ b/LCAforActiveSonarImaging/bin/la2pdf
@@ -53,15 +53,15 @@ fi
 echo ':)  SUCCESS: dvipdfmx'
   
   
-# Run bibtex:
-echo ':) Building bibliography..'
-bibtex ${1}.aux
-
-if [ $? -ne 0 ]; then
-   echo ':( FAILED: bibtex'
-   exit 1
-fi
-echo ':) SUCCESS: bibtex'
+# # Run bibtex:
+# echo ':) Building bibliography..'
+# bibtex ${1}.aux
+# 
+# if [ $? -ne 0 ]; then
+#    echo ':( FAILED: bibtex'
+#    exit 1
+# fi
+# echo ':) SUCCESS: bibtex'
 
 
 # Commit changes if it's about time to do so:
