la2pdf commit - 2015:07:28	19:48:39	(Tue28.Jul)

diff --git a/LCAforActiveSonarImaging/bin/la2pdf b/LCAforActiveSonarImaging/bin/la2pdf
--- a/LCAforActiveSonarImaging/bin/la2pdf
+++ b/LCAforActiveSonarImaging/bin/la2pdf
@@ -43,14 +43,14 @@ if [ $? -ne 0 ]; then
 fi
 echo ':)  SUCCESS: latex'
 
-# Converting from DVI to PDF:
-echo ':)  Starting dvipdfmx..'
-dvipdfmx ${1}.dvi
-if [ $? -ne 0 ]; then
-  echo ':(  FAILED: dvipdfmx'
-  exit 1
-fi
-echo ':)  SUCCESS: dvipdfmx'
+# # Converting from DVI to PDF:
+# echo ':)  Starting dvipdfmx..'
+# dvipdfmx ${1}.dvi
+# if [ $? -ne 0 ]; then
+#   echo ':(  FAILED: dvipdfmx'
+#   exit 1
+# fi
+# echo ':)  SUCCESS: dvipdfmx'
   
   
 # Run bibtex:
